title: NetCors
subtitle: Network Configuration and Tutorials
description: Network Configuration and Tutorials

exclude: ["README.md"]

gems: ["jekyll-lunr-js-search"]
lunr_search:
  js_dir: "assets/js"

authors:
  mukti:
    name: Muhamad Mukti
    site: mukti.website
    twitter: mmdmukti
    github: mmdmukti
    byline: Network and System Administrator